### ISSUE TITLE
Cannot find module mergeDicts

### ISSUE THREAD

**Issue by alii** [schummar/schummar-translate#18]
Trying to use schummar-translate in a basic Next.js app and running into the following error — 
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/25351731/159326984-ab9ff324-1203-43ce-884a-d74421a45dab.png">

**Comment by schummar** [comment]
Yes, the reason was missing file endings in the import paths, which some tools are strict about, but TypeScript doesn't like to put out (see https://github.com/microsoft/TypeScript/issues/16577)

I had that on my to do list for some time and now took the time to finally fix it. I did it by bundling the files with another build tool. Please try again with version 1.9.0.

**Comment by alii** [comment]
Awesome, thank you!

**Comment by schummar** [comment]
You're welcome 😀
